NOTE: You can open this sample inside an IDE using the https://www.jetbrains.com/help/idea/gradle.html#gradle_import_project_start[IntelliJ native importer] or https://projects.eclipse.org/projects/tools.buildship[Eclipse Buildship].

This sample shows how to aggregate code coverage across multiple Java subprojects using link:https://www.jacoco.org/jacoco/[JaCoCo].  The link:{userManualPath}/jacoco_report_aggregation_plugin.html[jacoco-report-aggregation plugin] provides this ability.

There are two ways to collect code coverage across multiple subprojects:

 1. From the distribution's project, such as an Android application or WAR subproject.
 2. Using a standalone project to specify subprojects.

=== Aggregate using distribution project
The distribution's runtime classpath will determine

=== Aggregate using standalone project

The project in this example contains three projects: `application`, `list` and `utilities`.  All three projects apply the `jacoco` plugin, and `application` consumes both `list` and `utilities` on its implementation configuration.  A fourth subproject `code-coverage-report` is the standalone project used to compute the coverage results.

====
include::sample[dir="groovy",files="code-coverage-report/build.gradle[]"]
include::sample[dir="kotlin",files="code-coverage-report/build.gradle.kts[]"]
====

A _convention plugin_ called `myproject.java-conventions` is applied to all the application and library projects, but not the standalone aggregation project above.  The standalone project applies `jacoco-report-aggregation` which
Here, the build is setup to run tests using link:https://junit.org/junit5[JUnit5] and we apply the `jacoco` plugin to collect the code coverage.
With the plugin applied, it automatically attaches itself to the `test` task to collect the code coverage.
Please refer to the link:{userManualPath}/jacoco_plugin.html[JaCoCo chapter] for more details on the plugin configuration.

Second, to generate a report spanning all our tested projects, we introduce and additional project `code-coverage-report` that collects source files and coverage data from all its dependent projects.
This is setup in a second  _convention plugin_ plugin called `myproject.jacoco-aggregation` which provides a task called `codeCoverageReport` to generate the aggregated report.

====
include::sample[dir="groovy",files="buildSrc/src/main/groovy/myproject.jacoco-aggregation.gradle[]"]
include::sample[dir="kotlin",files="buildSrc/src/main/kotlin/myproject.jacoco-aggregation.gradle.kts[]"]
====

Running the tests and generate the report:

[listing.terminal.sample-command]
----
$ ./gradlew codeCoverageReport

BUILD SUCCESSFUL
11 actionable tasks: 11 executed
----

For more information, see link:{userManualPath}/java_testing.html[Testing in Java project chapter].
